version: '3'

services:
  # MySQL 服务器服务
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: IoTdevice
      MYSQL_USER: hydra
      MYSQL_PASSWORD: password
    networks:
      iot:
        aliases:
          - mysql
    ports:
      - "3308:3306"
  # Next.js 应用程序服务
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mysql-db
    networks:
      iot:
        aliases:
          - nextjs
networks:
  iot:
    external: false